language: java
jdk:
  - openjdk8
script:
  - gradle build
jobs:
  include:
    - stage: "RUN MY TESTS"
      script: ./test
    - stage: "DEPLOY MY APP"
      script: ./deploy
addons:
  sonarcloud:
    organization: "sophabatch6"
    token:
      secure: "**************************" # encrypted value of your token

script:
  - ./gradlew sonarqube
