language: java
 jdk:
   - openjdk8
    
 notifications:
   email:
     - false
   webhooks: 
     - false
 jobs:
   include:
     - stage: "RUN MY TESTS"
       script: ./test
     - stage: "DEPLOY MY APP"
       if: branch = master
       script: ./deploy
