language: java
jdk:
  - openjdk8
script:
  - gradle build
jobs:
   include:
     - stage: "Unit Tests & SonarCloud Analysis"
       script:
         - gradle jacocoTestReport
         - gradle sonarqube -Dsonar.login=$Sophabatch6_JDBC -Dsonar.projectKey=$Sophabatch6_JDBC
addons:
  sonarcloud:
    organization: "sophabatch6"
    token:
      secure: $Sophabatch6_JDBC # encrypted value of your token

script:
  - ./gradlew sonarqube
