language: java
jdk:
  -openjdk8
script:
  -gradle build
jobs:
  include:
    - stage: "RUN MY TESTS"
      script: ./test
    - stage: "DEPLOY MY APP"
      if: branch = master
      script: ./deploy
notifications:
  email: false
  webhooks: false
